// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StageLabApi.Data;

#nullable disable

namespace StageLabApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260117222528_SeedEventActions")]
    partial class SeedEventActions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StageLabApi.Models.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Action");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Allows users to create event records",
                            Name = "CreateEvent"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Allows users to delete their own event record",
                            Name = "DeleteOwnEvent"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Allows users to delete any event record",
                            Name = "DeleteAnyEvent"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Allows users to edit their own event record",
                            Name = "EditOwnEvent"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Allows users to edit any event record",
                            Name = "EditAnyEvent"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Allows users to view their own event record",
                            Name = "ViewOwnEvent"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Allows users to view any event records",
                            Name = "ViewAnyEvent"
                        });
                });

            modelBuilder.Entity("StageLabApi.Models.ActionRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("RoleId");

                    b.ToTable("ActionRole");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            ActionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            ActionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            ActionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            ActionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            ActionId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 8,
                            ActionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            ActionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            ActionId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 11,
                            ActionId = 7,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("StageLabApi.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("StageLabApi.Models.EventUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("EventUser");
                });

            modelBuilder.Entity("StageLabApi.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Address2")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("StageLabApi.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("StageLabApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Role owned by administrator users in the arts org (has all actions assigned to them)",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Role owned by artist users in the arts org (has restricted actions)",
                            Name = "Artist"
                        });
                });

            modelBuilder.Entity("StageLabApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("StageLabApi.Models.ActionRole", b =>
                {
                    b.HasOne("StageLabApi.Models.Action", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageLabApi.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("StageLabApi.Models.Event", b =>
                {
                    b.HasOne("StageLabApi.Models.Location", "Location")
                        .WithMany("Events")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageLabApi.Models.Project", "Project")
                        .WithMany("Events")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Location");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("StageLabApi.Models.EventUser", b =>
                {
                    b.HasOne("StageLabApi.Models.Event", "Event")
                        .WithMany("EventUsers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageLabApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StageLabApi.Models.Event", b =>
                {
                    b.Navigation("EventUsers");
                });

            modelBuilder.Entity("StageLabApi.Models.Location", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("StageLabApi.Models.Project", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
